[package]
name = "csm-manager"
version = "0.1.0"
description = "Contract Social Manager - Desktop Manager App"
authors = ["you"]
edition = "2021"

[lib]
name = "csm_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-window-state = "2"
tauri-plugin-notification = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
